{{- if not .Values.storj.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthetics.fullname" . }}
  labels:
    {{- include "synthetics.labels" . | nindent 4 }}
type: Opaque
data:
  access-grant: {{ .Values.storj.accessGrant | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.s3.existingSecret) (or .Values.s3.accessKey .Values.s3.secretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthetics.fullname" . }}-s3
  labels:
    {{- include "synthetics.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.s3.secretKey | b64enc | quote }}
{{- end }}
